// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnldghbqeppxfviyephd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubGRnaGJxZXBweGZ2aXllcGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTkyODMsImV4cCI6MjA3NDA5NTI4M30.ss8JlhWsfwwa4kHu25IHOb3Nhj45m_vBgCuC4wEQf88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});